### ISSUE TITLE
Product on Strapi disappear after deleting on Medusa

### ISSUE THREAD

**Issue by minhtungo** [SGFGOV/medusa-strapi-repo#54]
**Describe the bug**
When I delete a product on Medusa's backend, all of the products on Strapi will disappear. I am not sure if this also happens for other data like categories or so on. 

**To Reproduce**
1. Go to Medusa Admin Dashboard 
2. Delete a product
3. See all the products on Strapi disappear.

**Expected behavior**
Only the product deleted on Medusa was removed on Strapi.

**Comment by SGFGOV** [comment]
Hi, can you share a video of the steps you take
