### ISSUE TITLE
Create New App - Strapi for medusa

### ISSUE THREAD

**Issue by shreshtadev** [SGFGOV/medusa-strapi-repo#70]
**Bug Description** 
_The type is required_

**To Reproduce**

1. create a new strapi app with the template
2. run with yarn develop or npm run develop

**Expected behavior**
See an admin ui @strapibaseurl

**Screenshots**
![image](https://github.com/SGFGOV/medusa-strapi-repo/assets/7456363/ea53a612-0a2a-4325-a820-e1d03ada4a0d)

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser: chrome
 - Node - v20.10.0

**Additional Context**
Could see that this is from content-manager plugin

**Comment by SGFGOV** [comment]
are you following the medusa js strapi integration documents or the  readme of this repo ?
